const md5Module = require('md5');

/**
 * use a specified string as patamenter, return an object which include a hash generated by md5
 * and a seed which was used as input of the md5 function.
 */
module.exports = function decryption(passwordValue, seed, passwordMd5Value) {
    let value = md5Module(seed + passwordValue);
    console.log(passwordMd5Value+'/n'+value);
    return passwordMd5Value === value;
}

